"""Generate calibration pieces and native Prusa XL projects from checked solids."""
import json, subprocess, sys, zipfile
from pathlib import Path
import numpy as np
import trimesh as tm
import build_modular_print as b
ROOT=b.ROOT;OUT=b.OUT
SLICER=Path('/Applications/Original Prusa Drivers/PrusaSlicer.app/Contents/MacOS/PrusaSlicer')

def config(src,changes,out):
    lines=src.read_text().splitlines();keys=set()
    for i,line in enumerate(lines):
        key=line.split(' = ')[0]
        if key in changes:lines[i]=f'{key} = {changes[key]}';keys.add(key)
    lines += [f'{k} = {v}' for k,v in changes.items() if k not in keys]
    out.write_text('\n'.join(lines)+'\n')

def embed_config(native,cfg):
    # PrusaSlicer's CLI geometry export omits the full settings bundle.
    # Use the same semicolon-prefixed format as its project exporter.
    with zipfile.ZipFile(native) as z:data={n:z.read(n) for n in z.namelist()}
    data['Metadata/Slic3r_PE.config']='; generated by PrusaSlicer 2.9.6, modular XTI-30 settings\n\n'+'\n'.join('; '+line for line in cfg.read_text().splitlines() if ' = ' in line)+'\n'
    data['Metadata/Prusa_Slicer_wipe_tower_information.xml']='<?xml version="1.0" encoding="utf-8"?><wipe_tower_information bed_idx="0" position_x="220" position_y="280" rotation_deg="0"/>'
    with zipfile.ZipFile(native,'w',zipfile.ZIP_DEFLATED) as z:
        for n,v in data.items():z.writestr(n,v)

def coupons():
    tests=[]
    # The horizontal holes reproduce the actual shoulder roof and print direction.
    block=b.box((12,14,39),(0,0,19.5))
    for z,r in zip([7,19.5,32],[4.2,4.3,4.35]):block-=b.tdhole(r,14,(0,0,z))
    m=b.shape_mesh(block);m.apply_transform(tm.transformations.euler_matrix(-np.pi/2,0,0));m.apply_translation(-m.bounds[0]);m.apply_translation((120,140,0));tests.append(('horizontal_8.4_8.6_8.7', [('ivory',m)]))
    block=b.box((39,14,7),(0,0,3.5))
    for x,r in zip([-12.5,0,12.5],[4.2,4.3,4.35]):block-=b.cyl(r,9,(x,0,3.5))
    m=b.shape_mesh(block);m.apply_translation((173,160,0));tests.append(('vertical_8.4_8.6_8.7',[('ivory',m)]))
    pin=b.cyl(6,2,(0,0,1))+b.cyl(4,12,(0,0,8))+b.cyl(3.7,1,(0,0,14.5))
    m=b.shape_mesh(pin);m.apply_translation((155,130,0));tests.append(('8mm_pin',[('ivory',m)]))
    # A mortise and tenon with the same 0.3 mm per-side clearance as the waist.
    socket=b.box((15,12,7),(0,0,3.5))-b.box((8.6,6.6,9),(0,0,3.5))
    key=b.box((12,10,2),(0,0,1))+b.box((8,6,7),(0,0,5.5))
    for name,v,x in [('key_socket',socket,183),('waist_key',key,205)]:
        m=b.shape_mesh(v);m.apply_translation((x,130,0));tests.append((name,[('ivory',m)]))
    b.write3mf(OUT/'plates/fit_coupons_geometry.3mf',tests)

def main():
    report=json.loads((OUT/'qa/geometry.json').read_text())
    assert report['mesh_pass'] and not report['intersections'], 'Build and validate the model first.'
    coupons()
    base=OUT/'qa/prusa_factory_profile.ini'
    subprocess.run([str(SLICER),'--printer-profile','Original Prusa XL - 5T Input Shaper 0.4 nozzle','--print-profile','0.15mm STRUCTURAL @XLIS 0.4','--material-profile','Prusament PLA @XLIS','--save',str(base)],check=True)
    changes={'perimeters':'4','top_solid_layers':'5','bottom_solid_layers':'5','fill_density':'20%','fill_pattern':'gyroid','support_material':'0','support_material_auto':'0','complete_objects':'0','elefant_foot_compensation':'0.15','brim_width':'3','external_perimeter_speed':'30','small_perimeter_speed':'20','first_layer_speed':'20','filament_colour':'#E1E4DC;#C33441;#334FA4;#70A644;#30333C','extruder_colour':'#E1E4DC;#C33441;#334FA4;#70A644;#30333C','wipe_tower_x':'220','wipe_tower_y':'280','wipe_tower_width':'45','binary_gcode':'0'}
    jobs=[]
    for name,source,extra in [('main_single_material','main_single_material',{'wipe_tower':'0'}),('main_five_color','main_five_color',{'wipe_tower':'1'}),('fit_coupons','fit_coupons_geometry',{'wipe_tower':'0','fill_density':'100%','fill_pattern':'rectilinear'})]:
        cfg=OUT/'plates'/f'{name}.ini';config(base,{**changes,**extra},cfg)
        native=OUT/'plates'/f'XL_{name}.3mf'
        log=OUT/'qa'/f'{name}_import.log'
        with log.open('w') as f:subprocess.run([str(SLICER),'--load',str(cfg),'--dont-arrange','--export-3mf','--output',str(native),str(OUT/'plates'/f'{source}.3mf')],stdout=f,stderr=subprocess.STDOUT,check=True)
        embed_config(native,cfg)
        jobs.append({'name':name,'file':str(native)})
    # The dome uses one material and exposed supports, in its own PETG project.
    petg=OUT/'qa/prusa_factory_petg_profile.ini'
    subprocess.run([str(SLICER),'--printer-profile','Original Prusa XL - 5T Input Shaper 0.4 nozzle','--print-profile','0.15mm STRUCTURAL @XLIS 0.4','--material-profile','Prusament PETG @XL','--save',str(petg)],check=True)
    cfg=OUT/'plates/dome.ini';config(petg,{**changes,'wipe_tower':'0','support_material':'1','support_material_auto':'1','support_material_buildplate_only':'1','support_material_style':'snug','support_material_threshold':'35','support_material_contact_distance':'0.2','support_material_bottom_contact_distance':'0.2','support_material_interface_layers':'3','support_material_extruder':'1','support_material_interface_extruder':'1','brim_width':'4','fill_density':'0%','perimeters':'3','external_perimeter_speed':'20'},cfg)
    native=OUT/'plates/XL_dome_PETG.3mf'
    with (OUT/'qa/dome_import.log').open('w') as f:subprocess.run([str(SLICER),'--load',str(cfg),'--dont-arrange','--export-3mf','--output',str(native),str(OUT/'plates/dome_geometry.3mf')],stdout=f,stderr=subprocess.STDOUT,check=True)
    embed_config(native,cfg)
    jobs.append({'name':'dome','file':str(native)})
    (OUT/'qa/slice_jobs.json').write_text(json.dumps(jobs,indent=2));print(json.dumps(jobs,indent=2))
if __name__=='__main__':main()
